# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    env:
      # See https://download.osgeo.org/qgis/win64
      QGIS_VERSION: QGIS-OSGeo4W-3.16.6-1

    steps:
      - uses: actions/checkout@v2
      
#      - name: Cache installer
#        id: cache-installer
#        uses: actions/cache@v2
#        with:
#          path: |
#            QGIS.msi
#            QGIS.exe
#          key: ${{ env.QGIS_VERSION }}-xx
          
      - name: Download QGIS
        if: steps.cache-installer.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri "https://download.osgeo.org/osgeo4w/osgeo4w-setup.exe" -OutFile osgeo4w-setup.exe
          
      - name: Install python stuff
        run: |
          # Load QGIS-3.16 LTR installer V1 (it comes with python 3.7 instead of 3.9 and other old deps to check)
          ./osgeo4w-setup.exe -g -k --autoaccept -q -d -o -P python3-tools,python3-pip,python3-setuptools -s "http://download.osgeo.org/osgeo4w/x86_64/"
        
      - name: Install python stuff
        run: |
          # Load QGIS-3.16 LTR installer V1 (it comes with python 3.7 instead of 3.9 and other old deps to check)
          ./osgeo4w-setup.exe -g -k --autoaccept -q -d -o -P qgis-ltr -s "http://download.osgeo.org/osgeo4w/x86_64/"
          
      - name: 🦨 Setup tmate session
        if: always()
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
