# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    env:
      # See https://download.osgeo.org/qgis/win64
      QGIS_VERSION: QGIS-OSGeo4W-3.16.6-1

    steps:
      - uses: actions/checkout@v2
      - name: Cache installer
        uses: actions/cache@v2
        with:
          path: |
            QGIS.msi
          key: ${{ env.QGIS_VERSION }}
      - name: Install QGIS
        run: |
          wget "https://download.osgeo.org/qgis/win64/${{ env.QGIS_VERSION }}.msi" -outfile "QGIS.msi"
          msiexec /i QGIS.msi
