# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    env:
      # See https://download.osgeo.org/qgis/win64
      QGIS_VERSION: QGIS-OSGeo4W-3.16.6-1

    steps:
      - uses: actions/checkout@v2
      
      - name: Cache installer
        id: cache-installer
        uses: actions/cache@v2
        with:
          path: |
            QGIS.msi
            QGIS.exe
          key: ${{ env.QGIS_VERSION }}-x
          
      - name: Download QGIS
        if: steps.cache-installer.outputs.cache-hit != 'true'
        run: |
          # Invoke-WebRequest -Uri "https://download.osgeo.org/qgis/win64/${{ env.QGIS_VERSION }}.msi" -OutFile "QGIS.msi"
          Invoke-WebRequest -Uri "http://download.osgeo.org/qgis/win64/QGIS-OSGeo4W-3.16.7-1-Setup-x86_64.exe" QGIS.exe
          
      - name: Install QGIS
        run: |
          msiexec.exe /i QGIS.msi
          
      - name: 🦨 Setup tmate session
        if: always()
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
