# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Install QGIS
        run: |
          (New-Object System.Net.WebClient).DownloadFile("https://download.osgeo.org/qgis/win64/QGIS-OSGeo4W-3.16.6-1.msi", "QGIS.msi")
          msiexec /i QGIS.msi
